### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create an html file with html skeleton
- [x] create a background for car to drive on
- [x] create a car img
- [x] the car img is at the top left corner
- [x] check CSS and delete any unnecessary codes
- [x] check bugs
